document:
  language: ru
  content: content
  root: content/root.md
  output: build/dissertation-gost-title-v10.docx
  assembled_markdown: build/assembled.md
  bibliography: bibliography/bibliography.bib
  csl: assets/csl/gost-r-7-0-5-2008-numeric.csl
  bibliography_title: СПИСОК ЛИТЕРАТУРЫ

page:
  size: A4
  margins:
    left: 25mm
    right: 10mm
    top: 20mm
    bottom: 20mm

numbering:
  figures: chapter
  tables: chapter
  equations: chapter
