default: dissertation

profiles:
  dissertation:
    size: A4
    orientation: portrait
    margins:
      left: 25mm
      right: 10mm
      top: 20mm
      bottom: 20mm

  appendix-wide:
    size: A4
    orientation: portrait
    margins:
      left: 10mm
      right: 10mm
      top: 15mm
      bottom: 15mm

  landscape:
    size: A4
    orientation: landscape
    margins:
      left: 20mm
      right: 10mm
      top: 15mm
      bottom: 15mm
