from __future__ import annotations

import shutil
import subprocess
import re
import hashlib
from copy import deepcopy
from pathlib import Path

import yaml
from docx import Document
from docx.enum.section import WD_ORIENT, WD_SECTION
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.text import WD_BREAK
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT, WD_TABLE_ALIGNMENT
from docx.enum.style import WD_STYLE_TYPE
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Mm, Pt, RGBColor


SECTION_MARKER_RE = re.compile(r"^\[\[SECTION:(?P<name>[a-z][a-z0-9_-]*)]]$")


def _number(value: str, suffix: str) -> float:
    text = str(value).strip().casefold()
    if not text.endswith(suffix):
        raise ValueError(f"expected a {suffix} value, got {value!r}")
    return float(text[: -len(suffix)])


def _set_font(style, family: str, size: str, bold: bool | None = None) -> None:
    style.font.name = family
    style.font.size = Pt(_number(size, "pt"))
    if bold is not None:
        style.font.bold = bold
    rpr = style.element.get_or_add_rPr()
    fonts = rpr.rFonts
    if fonts is None:
        fonts = OxmlElement("w:rFonts")
        rpr.insert(0, fonts)
    for attribute in ("ascii", "hAnsi", "eastAsia", "cs"):
        fonts.set(qn(f"w:{attribute}"), family)
    # Pandoc's reference document leaves theme font references on built-in
    # styles (for example majorHAnsi -> Aptos Display). Word may prefer those
    # references in the style gallery even when explicit font names exist.
    for attribute in ("asciiTheme", "hAnsiTheme", "eastAsiaTheme", "cstheme"):
        fonts.attrib.pop(qn(f"w:{attribute}"), None)


def _set_repeatable_styles(document: Document, styles: dict) -> None:
    body = styles["body"]
    family = body["font"]["family"]
    # Normalize the complete Word style set, including styles generated by
    # Pandoc that are not explicitly represented in styles.yaml.
    for style in document.styles:
        style.font.name = family
        rpr = style.element.get_or_add_rPr()
        fonts = rpr.rFonts
        if fonts is None:
            fonts = OxmlElement("w:rFonts")
            rpr.insert(0, fonts)
        for attribute in ("ascii", "hAnsi", "eastAsia", "cs"):
            fonts.set(qn(f"w:{attribute}"), family)
        for attribute in ("asciiTheme", "hAnsiTheme", "eastAsiaTheme", "cstheme"):
            fonts.attrib.pop(qn(f"w:{attribute}"), None)
    defaults = document.styles.element.find(qn("w:docDefaults"))
    default_rpr = defaults.find(f"{qn('w:rPrDefault')}/{qn('w:rPr')}") if defaults is not None else None
    if default_rpr is not None:
        default_fonts = default_rpr.find(qn("w:rFonts"))
        if default_fonts is None:
            default_fonts = OxmlElement("w:rFonts")
            default_rpr.insert(0, default_fonts)
        for attribute in ("ascii", "hAnsi", "eastAsia", "cs"):
            default_fonts.set(qn(f"w:{attribute}"), family)
        for attribute in ("asciiTheme", "hAnsiTheme", "eastAsiaTheme", "cstheme"):
            default_fonts.attrib.pop(qn(f"w:{attribute}"), None)
    normal = document.styles["Normal"]
    _set_font(normal, body["font"]["family"], body["font"]["size"])
    normal.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    normal.paragraph_format.line_spacing = float(body["line_spacing"])
    # Keep Normal neutral: Word rebuilds field-generated TOC styles from it.
    # The dissertation red line is applied directly to source body paragraphs
    # below, so generated fields do not inherit a 12.5 mm first-line indent.
    normal.paragraph_format.first_line_indent = Mm(0)
    normal.paragraph_format.space_before = Pt(_number(body["space_before"], "pt"))
    normal.paragraph_format.space_after = Pt(_number(body["space_after"], "pt"))

    mapping = (("Heading 1", "chapter"), ("Heading 2", "section"), ("Heading 3", "subsection"))
    for word_name, yaml_name in mapping:
        spec = styles["headings"][yaml_name]
        style = document.styles[word_name]
        _set_font(style, spec["font"]["family"], spec["font"]["size"], spec["font"].get("bold"))
        style.font.color.rgb = None
        style.paragraph_format.first_line_indent = Mm(0)
        style.paragraph_format.space_before = Pt(_number(spec.get("space_before", "0pt"), "pt"))
        style.paragraph_format.space_after = Pt(_number(spec.get("space_after", "0pt"), "pt"))
        style.paragraph_format.keep_with_next = True
        style.paragraph_format.page_break_before = bool(spec.get("page_break_before", False))
        style.paragraph_format.alignment = (
            WD_ALIGN_PARAGRAPH.CENTER if spec.get("alignment") == "center" else WD_ALIGN_PARAGRAPH.LEFT
        )

    if "Equation" not in document.styles:
        equation = document.styles.add_style("Equation", WD_STYLE_TYPE.PARAGRAPH)
    else:
        equation = document.styles["Equation"]
    equation.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
    equation.paragraph_format.first_line_indent = Mm(0)
    equation.paragraph_format.space_before = Pt(6)
    equation.paragraph_format.space_after = Pt(6)
    _set_font(equation, family, body["font"]["size"])

    for name, alignment, bold in (
        ("TOC Heading", WD_ALIGN_PARAGRAPH.CENTER, True),
        ("TOC 1", WD_ALIGN_PARAGRAPH.LEFT, False),
        ("TOC 2", WD_ALIGN_PARAGRAPH.LEFT, False),
        ("TOC 3", WD_ALIGN_PARAGRAPH.LEFT, False),
    ):
        style = next((item for item in document.styles if item.name.casefold() == name.casefold()), None)
        if style is None:
            continue
        _set_font(style, body["font"]["family"], body["font"]["size"], bold)
        style.font.color.rgb = RGBColor(0, 0, 0)
        style.paragraph_format.alignment = alignment
        style.paragraph_format.first_line_indent = Mm(0)
        style.paragraph_format.line_spacing = 1.0
        style.paragraph_format.space_before = Pt(0)
        style.paragraph_format.space_after = Pt(6 if name == "TOC Heading" else 0)
        if name != "TOC Heading":
            based_on = style.element.find(qn("w:basedOn"))
            if based_on is not None:
                style.element.remove(based_on)

    if "Bibliography" in document.styles:
        bibliography = document.styles["Bibliography"]
        _set_font(bibliography, body["font"]["family"], body["font"]["size"])
        bibliography.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        bibliography.paragraph_format.line_spacing = float(body["line_spacing"])
        bibliography.paragraph_format.left_indent = Mm(12.5)
        bibliography.paragraph_format.first_line_indent = Mm(-12.5)
        bibliography.paragraph_format.space_before = Pt(0)
        bibliography.paragraph_format.space_after = Pt(0)
        ppr = bibliography.element.get_or_add_pPr()
        tabs = ppr.find(qn("w:tabs"))
        if tabs is not None:
            ppr.remove(tabs)
        tabs = OxmlElement("w:tabs")
        tab = OxmlElement("w:tab")
        tab.set(qn("w:val"), "left")
        tab.set(qn("w:pos"), str(int(Mm(12.5).twips)))
        tabs.append(tab)
        ppr.append(tabs)

    # Pandoc's built-in Image Caption style is italic. A REF field copies the
    # target formatting, so suppressing italics only on the caption run can be
    # inverted by Word's toggle-property semantics. Make the style itself
    # upright and leave target runs free of local italic overrides.
    if "Image Caption" in document.styles:
        document.styles["Image Caption"].font.italic = False

    for name in ("Hyperlink", "FollowedHyperlink"):
        if name not in document.styles:
            continue
        hyperlink = document.styles[name]
        hyperlink.font.color.rgb = RGBColor(0, 0, 0)
        hyperlink.font.underline = False


def _add_page_number(paragraph) -> None:
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = paragraph.add_run()
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    instruction = OxmlElement("w:instrText")
    instruction.set(qn("xml:space"), "preserve")
    instruction.text = " PAGE "
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    run._r.extend((begin, instruction, end))


TARGET_RE = re.compile(
    r"\[\[TARGET:(?P<kind>table|figure|equation):(?P<id>[A-Za-z0-9_.-]+):"
    r"(?P<chapter>\d+):(?P<ordinal>\d+)]]"
)
REFERENCE_FIELD_RE = re.compile(
    r"\[\[(?P<form>REF|NUMBER):(?P<kind>table|figure|equation):"
    r"(?P<id>[A-Za-z0-9_.-]+):(?P<number>\d+(?:\.\d+)*)]]"
)
OBJECT_LIST_MARKER_RE = re.compile(r"^\[\[LIST:(?P<kind>figure|table)]]$")
STAT_FIELD_RE = re.compile(r"\[\[STAT:(?P<name>pages)]]")


def _bookmark_name(kind: str, object_id: str) -> str:
    digest = hashlib.sha1(f"{kind}:{object_id}".encode("utf-8")).hexdigest()[:16]
    return f"md_{kind[:3]}_{digest}"


def _field_run(instruction: str, display: str, rpr=None) -> OxmlElement:
    run = OxmlElement("w:r")
    if rpr is not None:
        run.append(deepcopy(rpr))
    field_rpr = run.find(qn("w:rPr"))
    if field_rpr is not None:
        for tag in ("i", "iCs"):
            italic = field_rpr.find(qn(f"w:{tag}"))
            if italic is not None:
                field_rpr.remove(italic)
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    begin.set(qn("w:dirty"), "true")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = f" {instruction} "
    separate = OxmlElement("w:fldChar")
    separate.set(qn("w:fldCharType"), "separate")
    text = OxmlElement("w:t")
    text.text = display
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    run.extend((begin, instr, separate, text, end))
    return run


def _text_run(text: str, rpr=None) -> OxmlElement:
    run = OxmlElement("w:r")
    if rpr is not None:
        run.append(deepcopy(rpr))
    node = OxmlElement("w:t")
    if text[:1].isspace() or text[-1:].isspace():
        node.set(qn("xml:space"), "preserve")
    node.text = text
    run.append(node)
    return run


def _tab_run() -> OxmlElement:
    run = OxmlElement("w:r")
    run.append(OxmlElement("w:tab"))
    return run


def _replace_markers_in_runs(paragraph, pattern: re.Pattern, replacement) -> int:
    replacements = 0
    for run in list(paragraph.runs):
        text = run.text
        matches = list(pattern.finditer(text))
        if not matches:
            continue
        parent = run._r.getparent()
        position = parent.index(run._r)
        rpr = run._r.find(qn("w:rPr"))
        nodes: list[OxmlElement] = []
        cursor = 0
        for match in matches:
            if match.start() > cursor:
                nodes.append(_text_run(text[cursor : match.start()], rpr))
            nodes.extend(replacement(match, rpr))
            cursor = match.end()
            replacements += 1
        if cursor < len(text):
            nodes.append(_text_run(text[cursor:], rpr))
        parent.remove(run._r)
        for offset, node in enumerate(nodes):
            parent.insert(position + offset, node)
    return replacements


def _sequence_nodes(match: re.Match, rpr, bookmark_id: int) -> list[OxmlElement]:
    kind = match["kind"]
    chapter = int(match["chapter"])
    ordinal = int(match["ordinal"])
    label = {"table": "Table", "figure": "Figure", "equation": "Equation"}[kind]
    bookmark = _bookmark_name(kind, match["id"])
    start = OxmlElement("w:bookmarkStart")
    start.set(qn("w:id"), str(bookmark_id))
    start.set(qn("w:name"), bookmark)
    end = OxmlElement("w:bookmarkEnd")
    end.set(qn("w:id"), str(bookmark_id))
    nodes = [start]
    if chapter:
        nodes.append(_text_run(f"{chapter}.", rpr))
    sequence_name = f"Md{label}Chapter{chapter}"
    nodes.append(_field_run(f"SEQ {sequence_name} \\* ARABIC", str(ordinal), rpr))
    nodes.append(end)
    return nodes


def _install_cross_reference_fields(document: Document) -> None:
    bookmark_id = 1000
    targets: set[tuple[str, str]] = set()
    captions: dict[str, list[tuple[str, str, str]]] = {"figure": [], "table": []}

    for paragraph in document.paragraphs:
        paragraph_text = paragraph.text
        target_matches = list(TARGET_RE.finditer(paragraph_text))
        for match in target_matches:
            if match["kind"] in captions:
                caption = paragraph_text[match.end() :].strip().lstrip("–-").strip()
                captions[match["kind"]].append(
                    (_bookmark_name(match["kind"], match["id"]), f"{match['chapter']}.{match['ordinal']}", caption)
                )

        def replace_target(match: re.Match, rpr):
            nonlocal bookmark_id
            key = (match["kind"], match["id"])
            if key in targets:
                raise ValueError(f"duplicate cross-reference target: {match['kind']}:{match['id']}")
            targets.add(key)
            nodes = _sequence_nodes(match, rpr, bookmark_id)
            bookmark_id += 1
            return nodes

        _replace_markers_in_runs(paragraph, TARGET_RE, replace_target)

    for paragraph in list(document.paragraphs):
        marker = OBJECT_LIST_MARKER_RE.match(paragraph.text.strip())
        if marker is None:
            continue
        kind = marker["kind"]
        label = "Рисунок" if kind == "figure" else "Таблица"
        for bookmark, number, caption in captions[kind]:
            item = OxmlElement("w:p")
            ppr = OxmlElement("w:pPr")
            justification = OxmlElement("w:jc")
            justification.set(qn("w:val"), "left")
            ppr.append(justification)
            indentation = OxmlElement("w:ind")
            indentation.set(qn("w:left"), "0")
            indentation.set(qn("w:firstLine"), "0")
            ppr.append(indentation)
            tabs = OxmlElement("w:tabs")
            tab = OxmlElement("w:tab")
            tab.set(qn("w:val"), "right")
            tab.set(qn("w:leader"), "dot")
            tab.set(qn("w:pos"), "9922")
            tabs.append(tab)
            ppr.append(tabs)
            item.append(ppr)
            item.append(_text_run(f"{label} "))
            item.append(_field_run(f"REF {bookmark} \\h", number))
            if caption:
                item.append(_text_run(f" – {caption}"))
            item.append(_tab_run())
            item.append(_field_run(f"PAGEREF {bookmark} \\h", "1"))
            paragraph._p.addprevious(item)
        paragraph._element.getparent().remove(paragraph._element)

    for paragraph in document.paragraphs:
        def replace_reference(match: re.Match, rpr):
            key = (match["kind"], match["id"])
            if key not in targets:
                raise ValueError(f"unknown cross-reference target: {match['kind']}:{match['id']}")
            kind = match["kind"]
            bookmark = _bookmark_name(kind, match["id"])
            display_number = match["number"]
            prefix = ""
            suffix = ""
            if match["form"] == "REF":
                prefix, suffix = {
                    "table": ("таблица ", ""),
                    "figure": ("рисунок ", ""),
                    "equation": ("(", ")"),
                }[kind]
            nodes: list[OxmlElement] = []
            if prefix:
                nodes.append(_text_run(prefix, rpr))
            nodes.append(_field_run(f"REF {bookmark} \\h", display_number, rpr))
            if suffix:
                nodes.append(_text_run(suffix, rpr))
            return nodes

        _replace_markers_in_runs(paragraph, REFERENCE_FIELD_RE, replace_reference)

        def replace_stat(match: re.Match, rpr):
            return [_field_run("NUMPAGES", "1", rpr)]

        _replace_markers_in_runs(paragraph, STAT_FIELD_RE, replace_stat)

    # Pandoc also copies a figure caption into wp:docPr/@descr as image alt
    # text. Keep the accessibility description readable and free of compiler
    # markers even though the visible caption has already become a SEQ field.
    for node in document._element.xpath(".//*[@descr]"):
        description = node.get("descr", "")
        node.set(
            "descr",
            TARGET_RE.sub(lambda match: f"{match['chapter']}.{match['ordinal']}", description),
        )


def _format_numbered_objects(document: Document, styles: dict) -> None:
    family = styles["body"]["font"]["family"]
    for paragraph in document.paragraphs:
        text = paragraph.text.strip()
        if text.startswith("Таблица "):
            paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
            paragraph.paragraph_format.first_line_indent = Mm(0)
            paragraph.paragraph_format.space_before = Pt(6)
            paragraph.paragraph_format.space_after = Pt(3)
        elif text.startswith("Рисунок "):
            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
            paragraph.paragraph_format.first_line_indent = Mm(0)
            paragraph.paragraph_format.space_before = Pt(3)
            paragraph.paragraph_format.space_after = Pt(6)
        else:
            continue
        for run in paragraph.runs:
            run.font.name = family
            run.font.size = Pt(14)
            run.italic = None

    usable_width_mm = 210 - _number(styles["document"]["margins"]["left"], "mm") - _number(
        styles["document"]["margins"]["right"], "mm"
    )
    usable_width = Mm(usable_width_mm)
    for shape in document.inline_shapes:
        properties = shape._inline.xpath(".//wp:docPr")
        description = properties[0].get("descr", "") if properties else ""
        # PDF appendix pages are also inline images internally, but their
        # 160 mm width is chosen to keep an A4 page inside the printable area.
        # Only semantic numbered figures are expanded to the full text width.
        if not description.casefold().startswith("рисунок "):
            continue
        if not shape.width:
            continue
        aspect_ratio = shape.height / shape.width
        shape.width = usable_width
        shape.height = int(usable_width * aspect_ratio)
    usable_height_mm = 297 - _number(styles["document"]["margins"]["top"], "mm") - _number(
        styles["document"]["margins"]["bottom"], "mm"
    )
    usable_height = Mm(usable_height_mm)
    # Treat every inline image consistently, including rasterized PDF pages in
    # appendices. Preserve proportions and use the full printable width unless
    # the image would become taller than the printable page.
    for shape in document.inline_shapes:
        if not shape.width:
            continue
        aspect_ratio = shape.height / shape.width
        target_width = usable_width
        target_height = int(target_width * aspect_ratio)
        if target_height > usable_height:
            target_height = usable_height
            target_width = int(target_height / aspect_ratio)
        shape.width = target_width
        shape.height = target_height
    for table in document.tables:
        if not table.rows or not table.columns:
            continue
        caption = table._tbl.tblPr.find(qn("w:tblCaption"))
        if caption is not None and caption.get(qn("w:val")) == "abstract-layout":
            continue
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        table.autofit = False
        table_properties = table._tbl.tblPr
        table_width = table_properties.find(qn("w:tblW"))
        if table_width is None:
            table_width = OxmlElement("w:tblW")
            table_properties.insert(0, table_width)
        table_width.set(qn("w:type"), "dxa")
        table_width.set(qn("w:w"), str(int(usable_width.twips)))
        borders = table_properties.find(qn("w:tblBorders"))
        if borders is None:
            borders = OxmlElement("w:tblBorders")
            table_properties.append(borders)
        else:
            for border in list(borders):
                borders.remove(border)
        for edge in ("top", "left", "bottom", "right", "insideH", "insideV"):
            border = OxmlElement(f"w:{edge}")
            border.set(qn("w:val"), "single")
            border.set(qn("w:sz"), "4")
            border.set(qn("w:color"), "000000")
            borders.append(border)
        column_width = Mm(usable_width_mm / len(table.columns))
        grid = table._tbl.tblGrid
        for grid_column in list(grid):
            grid.remove(grid_column)
        for _ in table.columns:
            grid_column = OxmlElement("w:gridCol")
            grid_column.set(qn("w:w"), str(int(column_width.twips)))
            grid.append(grid_column)
        for row_index, row in enumerate(table.rows):
            row._tr.get_or_add_trPr()
            if row_index == 0:
                header = OxmlElement("w:tblHeader")
                header.set(qn("w:val"), "true")
                row._tr.get_or_add_trPr().append(header)
            cannot_split = OxmlElement("w:cantSplit")
            row._tr.get_or_add_trPr().append(cannot_split)
            for cell in row.cells:
                cell.width = column_width
                cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
                tc_width = cell._tc.get_or_add_tcPr().find(qn("w:tcW"))
                if tc_width is not None:
                    tc_width.set(qn("w:type"), "dxa")
                    tc_width.set(qn("w:w"), str(int(column_width.twips)))
                for paragraph in cell.paragraphs:
                    paragraph.paragraph_format.first_line_indent = Mm(0)
                    paragraph.paragraph_format.line_spacing = 1.0
                    paragraph.paragraph_format.space_before = Pt(2)
                    paragraph.paragraph_format.space_after = Pt(2)
                    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER if row_index == 0 else WD_ALIGN_PARAGRAPH.LEFT
                    for run in paragraph.runs:
                        run.font.name = family
                        run.font.size = Pt(12)
                        if row_index == 0:
                            run.bold = True


def _format_numbered_equations(document: Document, styles: dict) -> None:
    marker_pattern = re.compile(
        r"^\[\[EQUATION:(?P<id>[A-Za-z0-9_.-]+):(?P<chapter>\d+):(?P<ordinal>\d+)]]$"
    )
    family = styles["body"]["font"]["family"]
    usable_width_mm = 210 - _number(styles["document"]["margins"]["left"], "mm") - _number(
        styles["document"]["margins"]["right"], "mm"
    )
    usable_twips = int(Mm(usable_width_mm).twips)

    paragraphs = list(document.paragraphs)
    for marker_index, marker in enumerate(paragraphs):
        match = marker_pattern.match(marker.text.strip())
        if match is None:
            continue
        formula = next(
            (candidate for candidate in paragraphs[marker_index + 1 :] if candidate._p.xpath(".//m:oMathPara")),
            None,
        )
        if formula is None:
            raise ValueError(f"equation marker {match.group(0)} is not followed by display math")

        # Match MathType's layout: one paragraph with a centered tab for the
        # editable OMML equation and a right tab for its number. Unlike a
        # borderless table, this cannot alter the geometry of adjacent tables.
        formula.alignment = WD_ALIGN_PARAGRAPH.LEFT
        formula.paragraph_format.first_line_indent = Mm(0)
        formula.paragraph_format.left_indent = Mm(0)
        formula.paragraph_format.right_indent = Mm(0)
        formula.paragraph_format.space_before = Pt(6)
        formula.paragraph_format.space_after = Pt(6)
        ppr = formula._p.get_or_add_pPr()
        tabs = ppr.find(qn("w:tabs"))
        if tabs is not None:
            ppr.remove(tabs)
        tabs = OxmlElement("w:tabs")
        for alignment, position in (("center", usable_twips // 2), ("right", usable_twips)):
            tab = OxmlElement("w:tab")
            tab.set(qn("w:val"), alignment)
            tab.set(qn("w:pos"), str(position))
            tabs.append(tab)
        ppr.append(tabs)

        math_para = formula._p.find(qn("m:oMathPara"))
        math = math_para.find(qn("m:oMath")) if math_para is not None else None
        if math is None:
            raise ValueError(f"equation marker {match.group(0)} has no Office Math object")
        math_para.remove(math)
        formula._p.remove(math_para)

        formula.add_run("\t")
        formula._p.append(math)
        formula.add_run("\t")
        number_run = formula.add_run(
            f"([[TARGET:equation:{match['id']}:{match['chapter']}:{match['ordinal']}]])"
        )
        number_run.font.name = family
        number_run.font.size = Pt(14)
        marker._element.getparent().remove(marker._element)


def _format_pdf_page_breaks(document: Document) -> None:
    paragraphs = list(document.paragraphs)
    for index, paragraph in enumerate(paragraphs):
        if paragraph.text.strip() != "[[PDF_PAGE_BREAK]]":
            continue
        if index + 1 < len(paragraphs):
            image_paragraph = paragraphs[index + 1]
            image_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
            image_paragraph.paragraph_format.first_line_indent = Mm(0)
            image_paragraph.paragraph_format.page_break_before = True
        paragraph._element.getparent().remove(paragraph._element)


def _load_section_profiles(project_root: Path, styles: dict) -> tuple[str, dict[str, dict]]:
    path = project_root / "config" / "sections.yaml"
    if path.is_file():
        data = yaml.safe_load(path.read_text(encoding="utf-8-sig")) or {}
    else:
        data = {}
    default_name = str(data.get("default", "dissertation"))
    profiles = data.get("profiles", {})
    if not isinstance(profiles, dict):
        raise ValueError("sections.profiles must be a mapping")
    if default_name not in profiles:
        profiles[default_name] = {
            "size": "A4",
            "orientation": "portrait",
            "margins": dict(styles["document"]["margins"]),
        }
    return default_name, profiles


def _apply_section_geometry(section, profile: dict, *, first: bool) -> None:
    if str(profile.get("size", "A4")).casefold() != "a4":
        raise ValueError("only A4 section profiles are supported")
    orientation = str(profile.get("orientation", "portrait")).casefold()
    if orientation == "portrait":
        section.orientation = WD_ORIENT.PORTRAIT
        section.page_width, section.page_height = Mm(210), Mm(297)
    elif orientation == "landscape":
        section.orientation = WD_ORIENT.LANDSCAPE
        section.page_width, section.page_height = Mm(297), Mm(210)
    else:
        raise ValueError(f"unsupported section orientation: {orientation}")
    margins = profile.get("margins", {})
    for name in ("left", "right", "top", "bottom"):
        if name not in margins:
            raise ValueError(f"section profile requires margins.{name}")
        setattr(section, f"{name}_margin", Mm(_number(margins[name], "mm")))
    section.start_type = WD_SECTION.NEW_PAGE
    section.different_first_page_header_footer = first


def _apply_section_profiles(document: Document, project_root: Path, styles: dict) -> None:
    default_name, profiles = _load_section_profiles(project_root, styles)
    active_names = [default_name]
    paragraphs = list(document.paragraphs)
    for index, marker in enumerate(paragraphs):
        match = SECTION_MARKER_RE.match(marker.text.strip())
        if match is None:
            continue
        profile_name = match["name"]
        if profile_name not in profiles:
            raise ValueError(f"unknown section profile: {profile_name}")
        previous = next((item for item in reversed(paragraphs[:index]) if item._element.getparent() is not None), None)
        if previous is None:
            raise ValueError("a section marker must follow document content")
        ppr = previous._p.get_or_add_pPr()
        old = ppr.find(qn("w:sectPr"))
        if old is not None:
            ppr.remove(old)
        ppr.append(deepcopy(document._element.body.sectPr))
        marker._element.getparent().remove(marker._element)
        active_names.append(profile_name)
    sections = list(document.sections)
    if len(sections) != len(active_names):
        raise ValueError("section marker conversion produced an inconsistent DOCX")
    for index, (section, name) in enumerate(zip(sections, active_names)):
        _apply_section_geometry(section, profiles[name], first=index == 0)
        # Word requires header/footer references to precede other section
        # properties and is sensitive to their canonical type order.
        sect_pr = section._sectPr
        references = list(sect_pr.findall(qn("w:headerReference"))) + list(
            sect_pr.findall(qn("w:footerReference"))
        )
        order = {"default": 0, "even": 1, "first": 2}
        references.sort(
            key=lambda item: (
                0 if item.tag == qn("w:headerReference") else 1,
                order.get(item.get(qn("w:type"), "default"), 9),
            )
        )
        for item in references:
            sect_pr.remove(item)
        for item in reversed(references):
            sect_pr.insert(0, item)


def _body_section_indexes(document: Document) -> dict[object, int]:
    indexes: dict[object, int] = {}
    section_index = 0
    for child in document._element.body.iterchildren():
        indexes[child] = section_index
        if child.find("./w:pPr/w:sectPr", namespaces=child.nsmap) is not None:
            section_index += 1
    return indexes


def _body_child(element, body):
    current = element
    while current is not None and current.getparent() is not body:
        current = current.getparent()
    return current


def _fit_objects_to_sections(document: Document) -> None:
    body = document._element.body
    indexes = _body_section_indexes(document)
    sections = list(document.sections)
    for shape in document.inline_shapes:
        child = _body_child(shape._inline, body)
        section = sections[indexes.get(child, 0)]
        usable_width = section.page_width - section.left_margin - section.right_margin
        usable_height = section.page_height - section.top_margin - section.bottom_margin
        if not shape.width:
            continue
        ratio = shape.height / shape.width
        target_width = usable_width
        target_height = int(target_width * ratio)
        if target_height > usable_height:
            target_height = usable_height
            target_width = int(target_height / ratio)
        shape.width, shape.height = target_width, target_height
    for table in document.tables:
        caption = table._tbl.tblPr.find(qn("w:tblCaption"))
        if caption is not None and caption.get(qn("w:val")) == "abstract-layout":
            continue
        child = _body_child(table._tbl, body)
        section = sections[indexes.get(child, 0)]
        usable_width = section.page_width - section.left_margin - section.right_margin
        table_width = table._tbl.tblPr.find(qn("w:tblW"))
        if table_width is not None:
            table_width.set(qn("w:type"), "dxa")
            table_width.set(qn("w:w"), str(int(usable_width / 635)))
        if table.columns:
            column_width = int(usable_width / len(table.columns))
            for grid_column in table._tbl.tblGrid:
                grid_column.set(qn("w:w"), str(int(column_width / 635)))
            for row in table.rows:
                for cell in row.cells:
                    cell.width = column_width
                    tc_width = cell._tc.get_or_add_tcPr().find(qn("w:tcW"))
                    if tc_width is not None:
                        tc_width.set(qn("w:type"), "dxa")
                        tc_width.set(qn("w:w"), str(int(column_width / 635)))


def _add_title_paragraph(
    document: Document,
    text: str,
    *,
    alignment,
    bold=False,
    before=0,
    after=0,
    line_spacing=1.5,
    size=14,
):
    paragraph = document.add_paragraph()
    paragraph.alignment = alignment
    paragraph.paragraph_format.first_line_indent = Mm(0)
    paragraph.paragraph_format.line_spacing = float(line_spacing)
    paragraph.paragraph_format.space_before = Pt(before)
    paragraph.paragraph_format.space_after = Pt(after)
    run = paragraph.add_run(text)
    run.bold = bold
    run.font.name = "Times New Roman"
    run.font.size = Pt(size)
    rpr = run._element.get_or_add_rPr()
    fonts = rpr.rFonts
    if fonts is None:
        fonts = OxmlElement("w:rFonts")
        rpr.insert(0, fonts)
    for attribute in ("ascii", "hAnsi", "eastAsia", "cs"):
        fonts.set(qn(f"w:{attribute}"), "Times New Roman")
    return paragraph


def _section_break_on(paragraph, template, *, hide_headers: bool = True) -> None:
    sect_pr = deepcopy(template)
    if hide_headers:
        for tag in ("w:headerReference", "w:footerReference", "w:titlePg"):
            for item in list(sect_pr.findall(qn(tag))):
                sect_pr.remove(item)
    section_type = sect_pr.find(qn("w:type"))
    if section_type is None:
        section_type = OxmlElement("w:type")
        sect_pr.insert(0, section_type)
    section_type.set(qn("w:val"), "nextPage")
    paragraph._p.get_or_add_pPr().append(sect_pr)


def _prepend_abstract_front_matter(document: Document, metadata: dict, abstract_config: dict) -> None:
    specialty = metadata.get("specialty", {})
    supervisor = metadata.get("supervisor", {})
    defense = abstract_config.get("defense", {})
    layout = abstract_config.get("layout", {})
    spacing = layout.get("title_spacing", {})
    title_size = _number(layout.get("title_font_size", "11pt"), "pt")
    verso_size = _number(layout.get("verso_font_size", "10pt"), "pt")
    body = document._element.body
    template = body.sectPr
    elements = []

    def add(text, alignment=WD_ALIGN_PARAGRAPH.CENTER, bold=False, after=0, size=None):
        paragraph = _add_title_paragraph(
            document, str(text), alignment=alignment, bold=bold, after=after,
            line_spacing=1.0, size=title_size if size is None else size,
        )
        elements.append(paragraph)
        return paragraph

    def set_run(run, *, bold=False):
        run.bold = bold
        run.font.name = "Times New Roman"
        run.font.size = Pt(verso_size)
        fonts = run._element.get_or_add_rPr().get_or_add_rFonts()
        for attribute in ("ascii", "hAnsi", "eastAsia", "cs"):
            fonts.set(qn(f"w:{attribute}"), "Times New Roman")

    def add_verso(text, alignment=WD_ALIGN_PARAGRAPH.JUSTIFY, after=0):
        return add(text, alignment=alignment, after=after, size=verso_size)

    def add_tabbed(parts, *, tab_mm=50.01, after=0):
        paragraph = add_verso("", after=after)
        paragraph.paragraph_format.tab_stops.add_tab_stop(Mm(tab_mm))
        for text, bold in parts:
            set_run(paragraph.add_run(text), bold=bold)
        return paragraph

    add("На правах рукописи", WD_ALIGN_PARAGRAPH.RIGHT,
        after=_number(spacing.get("manuscript_after", "36pt"), "pt"))
    author_name = str(metadata.get("author", {}).get("full_name", ""))
    author_surname, _, author_rest = author_name.partition(" ")
    add(author_surname.upper() + (" " + author_rest if author_rest else ""), bold=True,
        after=_number(spacing.get("author_after", "54pt"), "pt"))
    add(metadata.get("title", "").upper(), bold=True,
        after=_number(spacing.get("title_after", "48pt"), "pt"))
    add(f"{specialty.get('code', '')} – {specialty.get('name', '')}", bold=True,
        after=_number(spacing.get("specialty_after", "90pt"), "pt"))
    add("АВТОРЕФЕРАТ", bold=True)
    add("диссертации на соискание ученой степени", bold=True)
    add(metadata.get("degree", ""), bold=True,
        after=_number(spacing.get("abstract_after", "114pt"), "pt"))
    first_last = add(f"{metadata.get('city', '')} – {metadata.get('year', '')}", bold=True)
    first_last.add_run().add_break(WD_BREAK.PAGE)

    organization = str(defense.get("organization", "[указать]"))
    unit = str(defense.get("organization_unit", "")).strip()
    add_verso(f"Работа выполнена в {organization}" + (f" в {unit}" if unit else ""), after=30)

    supervisor_name = str(supervisor.get("full_name", ""))
    surname, _, rest = supervisor_name.partition(" ")
    degree_title = "д-р техн. наук, " + str(supervisor.get("title", "профессор"))
    add_tabbed([("Научный руководитель:", False), ("\t" + degree_title, False)])
    add_tabbed([("\t", False), (surname.upper() + (" " + rest if rest else ""), True)], after=24)

    for index, opponent in enumerate(defense.get("opponents", [])):
        if isinstance(opponent, dict):
            degree = str(opponent.get("degree", ""))
            name = str(opponent.get("full_name", ""))
        else:
            degree, name = str(opponent), ""
        label = "Официальные оппоненты:" if index == 0 else ""
        add_tabbed([(label, False), ("\t" + degree, False)])
        add_tabbed([("\t" + name, False)], after=36 if index == 0 else 30)

    add_tabbed([
        ("Ведущая организация:", False),
        ("\t" + str(defense.get("leading_organization", "[указать]")), False),
    ], after=72)
    add_verso(
        f"Защита диссертации состоится {defense.get('date', '[указать дату]')} в {defense.get('time', '[указать время]')} "
        f"на заседании диссертационного совета {defense.get('council', '[указать шифр]')} по адресу: "
        f"{defense.get('address', '[указать адрес]')}.", after=18,
    )
    add_verso(
        f"С диссертацией можно ознакомиться в {defense.get('library', '[указать библиотеку]')} "
        f"и на сайте {defense.get('website', '[указать сайт]')}.", after=42,
    )
    add("Автореферат разослан " + str(defense.get("mailing_date", "[указать дату]")) + ".",
        WD_ALIGN_PARAGRAPH.CENTER, after=36, size=verso_size)
    add_verso("Учёный секретарь")
    add_verso("диссертационного совета")
    second_last = add_tabbed([
        (str(defense.get("secretary_degree", "[указать степень]")), False),
        ("\t" + str(defense.get("secretary", "[указать секретаря]")), False),
    ], tab_mm=92.52)
    _section_break_on(second_last, template)

    title_pg = template.find(qn("w:titlePg"))
    if title_pg is not None:
        template.remove(title_pg)
    pg_num = template.find(qn("w:pgNumType"))
    if pg_num is None:
        pg_num = OxmlElement("w:pgNumType")
        template.append(pg_num)
    pg_num.set(qn("w:start"), "1")
    for index, paragraph in enumerate(elements):
        body.insert(index, paragraph._p)


def _prepend_title_page(document: Document, metadata: dict) -> None:
    organization = metadata.get("organization", {}).get("full_name", "")
    author = metadata.get("author", {}).get("full_name", "")
    specialty = metadata.get("specialty", {})
    supervisor = metadata.get("supervisor", {})
    elements = []

    if organization:
        elements.append(
            _add_title_paragraph(
                document,
                organization,
                alignment=WD_ALIGN_PARAGRAPH.CENTER,
                before=24,
                after=24,
            )
        )
    elements.append(
        _add_title_paragraph(
            document,
            "На правах рукописи",
            alignment=WD_ALIGN_PARAGRAPH.RIGHT,
            before=24,
            after=24,
        )
    )
    if author:
        elements.append(
            _add_title_paragraph(document, author, alignment=WD_ALIGN_PARAGRAPH.CENTER, before=0, after=8)
        )
    elements.append(
        _add_title_paragraph(
            document,
            str(metadata.get("title", "")).upper(),
            alignment=WD_ALIGN_PARAGRAPH.CENTER,
            bold=True,
            before=42,
            after=42,
        )
    )
    if specialty.get("code") or specialty.get("name"):
        specialty_text = " ".join(
            item
            for item in (
                f"Специальность {specialty['code']}" if specialty.get("code") else "",
                "–" if specialty.get("code") and specialty.get("name") else "",
                specialty.get("name", ""),
            )
            if item
        )
        elements.append(
            _add_title_paragraph(
                document,
                specialty_text,
                alignment=WD_ALIGN_PARAGRAPH.CENTER,
                before=24,
                after=24,
            )
        )
    dissertation_text = metadata.get("document_type", "Диссертация")
    if metadata.get("degree"):
        dissertation_text += f" на соискание ученой степени {metadata['degree']}"
    if dissertation_text:
        elements.append(
            _add_title_paragraph(
                document,
                dissertation_text,
                alignment=WD_ALIGN_PARAGRAPH.CENTER,
                before=24,
                after=24,
            )
        )
    if any(supervisor.get(key) for key in ("degree", "title", "full_name")):
        elements.append(
            _add_title_paragraph(
                document,
                "Научный руководитель:",
                alignment=WD_ALIGN_PARAGRAPH.LEFT,
                after=8,
                line_spacing=1.16,
            )
        )
        degree_and_title = ", ".join(
            item for item in (supervisor.get("degree", ""), supervisor.get("title", "")) if item
        )
        if degree_and_title:
            elements.append(
                _add_title_paragraph(
                    document,
                    degree_and_title,
                    alignment=WD_ALIGN_PARAGRAPH.LEFT,
                    after=8,
                    line_spacing=1.16,
                )
            )
        if supervisor.get("full_name"):
            elements.append(
                _add_title_paragraph(
                    document,
                    supervisor["full_name"],
                    alignment=WD_ALIGN_PARAGRAPH.LEFT,
                    after=84,
                    line_spacing=1.16,
                )
            )
    place = " – ".join(str(item) for item in (metadata.get("city", ""), metadata.get("year", "")) if item)
    last = _add_title_paragraph(document, place, alignment=WD_ALIGN_PARAGRAPH.CENTER)
    last.add_run().add_break(WD_BREAK.PAGE)
    elements.append(last)

    body = document._element.body
    for index, paragraph in enumerate(elements):
        body.insert(index, paragraph._p)


def _request_field_updates(document: Document) -> None:
    settings = document.settings.element
    update = settings.find(qn("w:updateFields"))
    if update is None:
        update = OxmlElement("w:updateFields")
        settings.append(update)
    update.set(qn("w:val"), "true")


def render_docx(
    project_root: Path,
    markdown_path: Path,
    output_path: Path,
    *,
    bibliography: Path | None = None,
    publications_bibliography: Path | None = None,
    csl: Path | None = None,
    bibliography_title: str = "СПИСОК ЛИТЕРАТУРЫ",
    document_kind: str = "dissertation",
) -> Path:
    pandoc = shutil.which("pandoc")
    if pandoc is None:
        raise RuntimeError("Pandoc is required for the DOCX math backend")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    command = [
            pandoc,
            str(markdown_path),
            "--from=markdown+tex_math_dollars",
            "--to=docx",
            "--metadata=lang:ru-RU",
    ]
    if document_kind == "dissertation":
        command.extend(["--toc", "--toc-depth=3", "--metadata=toc-title:ОГЛАВЛЕНИЕ"])
    bibliographies = [path for path in (bibliography, publications_bibliography) if path is not None]
    if bibliographies:
        command.append("--citeproc")
        for path in bibliographies:
            command.extend(["--bibliography", str(path)])
        command.append(f"--metadata=reference-section-title:{bibliography_title}")
    if csl is not None:
        command.extend(["--csl", str(csl)])
    command.extend(["--output", str(output_path)])
    subprocess.run(
        command,
        cwd=project_root,
        check=True,
    )
    styles = yaml.safe_load((project_root / "config" / "styles.yaml").read_text(encoding="utf-8-sig"))
    metadata = yaml.safe_load((project_root / "config" / "metadata.yaml").read_text(encoding="utf-8-sig")) or {}
    abstract_config = {}
    if document_kind == "abstract":
        abstract_config = yaml.safe_load((project_root / "config" / "abstract.yaml").read_text(encoding="utf-8-sig")) or {}
        layout = abstract_config.get("layout", {})
        styles["document"]["margins"] = layout.get("margins", styles["document"]["margins"])
        styles["body"]["font"]["size"] = layout.get("font_size", "12pt")
        styles["body"]["line_spacing"] = layout.get("line_spacing", 1.0)
        styles["body"]["first_line_indent"] = layout.get("first_line_indent", "10mm")
        for heading in styles["headings"].values():
            heading["font"]["size"] = layout.get("font_size", "11pt")
    document = Document(output_path)
    page = styles["document"]
    for section in document.sections:
        if document_kind == "abstract" and str(abstract_config.get("layout", {}).get("page_size", "A5")).casefold() == "a5":
            section.page_width = Mm(148)
            section.page_height = Mm(210)
        else:
            section.page_width = Mm(210)
            section.page_height = Mm(297)
        section.left_margin = Mm(_number(page["margins"]["left"], "mm"))
        section.right_margin = Mm(_number(page["margins"]["right"], "mm"))
        section.top_margin = Mm(_number(page["margins"]["top"], "mm"))
        section.bottom_margin = Mm(_number(page["margins"]["bottom"], "mm"))
        section.header_distance = Mm(_number(page["header_distance"], "mm"))
        section.footer_distance = Mm(_number(page["footer_distance"], "mm"))
        section.different_first_page_header_footer = True
        section.first_page_header.paragraphs[0].clear()
        page_numbers = styles.get("page_numbers", {})
        if page_numbers.get("position", "top-center") == "top-center":
            header = section.header
            header.paragraphs[0].clear()
            _add_page_number(header.paragraphs[0])
        else:
            footer = section.footer
            footer.paragraphs[0].clear()
            _add_page_number(footer.paragraphs[0])
    _set_repeatable_styles(document, styles)
    body_first_line_indent = Mm(_number(styles["body"]["first_line_indent"], "mm"))
    for paragraph in document.paragraphs:
        if paragraph.style.name in {"Normal", "First Paragraph"}:
            paragraph.paragraph_format.first_line_indent = body_first_line_indent
    first_chapter = next((p for p in document.paragraphs if p.style.name == "Heading 1"), None)
    if first_chapter is not None:
        # Pandoc already places the document body after the TOC. Suppressing
        # the inherited chapter page break here avoids an empty page between
        # the TOC and chapter 1 while later chapters still start on new pages.
        first_chapter.paragraph_format.page_break_before = False
    if document_kind == "abstract":
        _prepend_abstract_front_matter(document, metadata, abstract_config)
    else:
        _prepend_title_page(document, metadata)
    _request_field_updates(document)
    _format_numbered_objects(document, styles)
    _format_numbered_equations(document, styles)
    _install_cross_reference_fields(document)
    _format_pdf_page_breaks(document)
    if document_kind == "dissertation":
        _apply_section_profiles(document, project_root, styles)
    _fit_objects_to_sections(document)
    for paragraph in document.paragraphs:
        if paragraph._p.xpath(".//m:oMathPara"):
            paragraph.style = document.styles["Equation"]
        if paragraph.style.name in {"Heading 1", "Heading 2", "Heading 3"}:
            for run in paragraph.runs:
                run.font.name = body_family = styles["body"]["font"]["family"]
                rpr = run._element.get_or_add_rPr()
                fonts = rpr.rFonts
                if fonts is None:
                    fonts = OxmlElement("w:rFonts")
                    rpr.insert(0, fonts)
                for attribute in ("ascii", "hAnsi", "eastAsia", "cs"):
                    fonts.set(qn(f"w:{attribute}"), body_family)
                for attribute in ("asciiTheme", "hAnsiTheme", "eastAsiaTheme", "cstheme"):
                    fonts.attrib.pop(qn(f"w:{attribute}"), None)
    document.core_properties.title = "Автореферат" if document_kind == "abstract" else "Демонстрационная сборка диссертации"
    document.core_properties.subject = "Markdown to DOCX compiler preview"
    document.save(output_path)
    return output_path
